// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtpXbWMHssV_ZCd9hzvzngVSAfUE_l_7U',
    appId: '1:310244616336:web:a6984fc1ddb1137b649015',
    messagingSenderId: '310244616336',
    projectId: 'ridewave-f5460',
    authDomain: 'ridewave-f5460.firebaseapp.com',
    storageBucket: 'ridewave-f5460.appspot.com',
    measurementId: 'G-45TGW6HQ6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6swUZxQBa27Bw2jQ2uM5IV-QMUpOxL3E',
    appId: '1:310244616336:android:cb5f663e0ff9345c649015',
    messagingSenderId: '310244616336',
    projectId: 'ridewave-f5460',
    storageBucket: 'ridewave-f5460.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlglhJBcENnsQ2abgR7-2ChYdQGosK9Xs',
    appId: '1:310244616336:ios:a8fe30db38619f94649015',
    messagingSenderId: '310244616336',
    projectId: 'ridewave-f5460',
    storageBucket: 'ridewave-f5460.appspot.com',
    iosBundleId: 'com.ridewave.rideWave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlglhJBcENnsQ2abgR7-2ChYdQGosK9Xs',
    appId: '1:310244616336:ios:a8fe30db38619f94649015',
    messagingSenderId: '310244616336',
    projectId: 'ridewave-f5460',
    storageBucket: 'ridewave-f5460.appspot.com',
    iosBundleId: 'com.ridewave.rideWave',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtpXbWMHssV_ZCd9hzvzngVSAfUE_l_7U',
    appId: '1:310244616336:web:eb607c3fc62f9b83649015',
    messagingSenderId: '310244616336',
    projectId: 'ridewave-f5460',
    authDomain: 'ridewave-f5460.firebaseapp.com',
    storageBucket: 'ridewave-f5460.appspot.com',
    measurementId: 'G-M2MWTS84X9',
  );
}
